### ISSUE TITLE
Compatible to octave?

### ISSUE THREAD

**Issue by stefano2734** [byrneta/Computational-Fluid-Dynamics#1]
Are this exemples compatible to octave?

than you can extend your infos about this.

**Comment by byrneta** [comment]
I just checked all four examples and they work in GNU Octave. Thanks for the suggestion.

**Comment by stefano2734** [comment]
Great, please make a info of success with octave in Readme with version of octave. 
or successful tested with octave 7.2.
In search words octave and Cfd are also fine for the user.
So users can find octave compatible projects to work without matlab license.
